app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),

    path('week/', views.WeekCalendar.as_view(), name='week'),
    path('week/<int:year>/<int:month>/<int:day>', views.WeekCalendar.as_view(), name='week'),

    path('week_sch/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    path('week_sch/<int:year>/<int:month>/<int:day>', views.WeekWithScheduleCalendar.as_view(),
         name='week_with_schedule'),

    path('month_sch/', views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_sch/<int:year>/<int:month>/', views.MonthWithScheduleCalendar.as_view(),
         name='month_with_schedule'),

    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'),

]

make_calendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    summary = models.CharField('요약', max_length=50)
    description = models.TextField('상세설명', blank=True)
    start_time = models.TimeField('시작시간', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('완료시간', default=datetime.time(7, 0, 0))
    date = models.DateField('일자')
    created_at = models.DateTimeField('작성일', default=timezone.now)

    def __str__(self):
        return self.summary

app/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        # widget을 사용해 html input태그 생성
        widgets = {
            'summary': forms.TextInput(attrs={'class': 'form-control', }),
            'description': forms.Textarea(attrs={'class': 'form-control', }),
            'start_time': forms.TextInput(attrs={'class': 'form-control', }),
            'end_time': forms.TextInput(attrs={'class': 'form-control', }),
        }

    def clean_end_time(self):
        # cleaned_data : is_valid()함수로 값이 유효한 경우 여기에 저장된다고
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError('end time is faster than start time')
        return end_time

app/views.py
import datetime
from django.shortcuts import redirect
from django.views import generic
from . import mixins
from .forms import ScheduleForm
from .models import Schedule

# Create your views here.


class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    template_name = 'app/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    template_name = 'app/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    template_name = 'app/week_sch.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    template_name = 'app/month_sch.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    template_name = "app/mycalendar.html"
    model = Schedule
    date_field = 'date'
    form_class = ScheduleForm

    # 캘린더 정보 취득용
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('app:mycalendar', year=date.year, month=date.month, day=date.day)

app/templates/app/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Calendar</title>
</head>
<body>

<div class="container" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

app/templates/app/includes/month.html
<a href="{% url 'app:mycalendar' month_previous.year month_previous.month month_previous.day %}">last month</a>
{{ month_current | date:"Y/m" }}
<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">next month</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}

                <a href="{% url 'app:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

app/templates/app/includes/week.html
<a href="{% url 'app:mycalendar' week_previous.year week_previous.month  week_previous.day %}">last week</a>
{{ week_first | date:"Y/m/d/" }}〜{{ week_last | date:"Y/m/d/" }}
<a href="{% url 'app:mycalendar' week_next.year week_next.month  week_next.day %}">next week</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
            {% if now == day %}
                <td class="table-success">
                    {% else %}
                <td>
            {% endif %}
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    {{ s.summary }}<br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>

app/templates/app/month.html
{% extends 'app/base.html' %}

{% block content %}
    <a href="{% url 'app:month' month_previous.year month_previous.month %}">last month</a>
    {{ month_current | date:"Y/m" }}
    <a href="{% url 'app:month' month_next.year month_next.month %}">next month</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/app/month_sch.html
{% extends 'app/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
    <a href="{% url 'app:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'app:month_with_schedule' month_next.year month_next.month %}">次月</a>
    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}

                    {% for schedule in schedules %}
                        <p>{{ schedule.summary }}</p>
                    {% endfor %}
                </div>
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/app/mycalendar.html
{% extends 'app/base.html' %}
{% block content %}
    <div class="row">
        <!-- 왼쪽(col-md-3): 월간 캘린더와 스케줄 등록 폼/
         오른쪽(col-md-9): 주간 캘린더 with 스케줄입니다.-->
        <div class="col-md-3">
            {% include 'app/includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">전송</button>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'app/includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

app/templates/app/week.html
{% extends 'app/base.html' %}

{% block content %}
    <a href="{% url 'app:week' week_previous.year week_previous.month week_previous.day %}">last week</a>
    {{ week_first | date:"Y/m/d" }} ~ {{ week_last | date:"Y/m/d" }}
    <a href="{% url 'app:week' week_next.year week_next.month week_next.day %}">next week</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}

            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}

            </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

app/templates/app/week_sch.html
{% extends 'app/base.html' %}
{% block content %}

    <a href="{% url 'app:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">last week</a>
    {{ week_first | date:"Y/m/d/" }}〜{{ week_last | date:"Y/m/d/" }}
    <a href="{% url 'app:week_with_schedule' week_next.year week_next.month  week_next.day %}">next week</a>

    <table class="table table-bordered">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        <tr>
            {% for schedules in week_day_schedules.values %}
                <td>
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.summary }}<br>
                        {{ s.description | linebreaks }}
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
</head>
<body>

<div class="container" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>